import os
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.graphics.shapes import Drawing, Rect, String, Line
from flask import current_app

def draw_certificate_background(canvas, doc):
    """
    Draws decorative border and watermark background for Learning Hub L&D Certificate.
    """
    canvas.saveState()
    width, height = doc.pagesize

    # Outer Border (Navy Blue)
    canvas.setStrokeColor(colors.HexColor('#003366'))
    canvas.setLineWidth(5)
    canvas.rect(20, 20, width - 40, height - 40)

    # Inner Gold Decorative Border
    canvas.setStrokeColor(colors.HexColor('#D4AF37'))
    canvas.setLineWidth(1.5)
    canvas.rect(26, 26, width - 52, height - 52)

    # Top Header Banner
    canvas.setFillColor(colors.HexColor('#003366'))
    canvas.rect(26, height - 80, width - 52, 54, fill=1, stroke=0)

    # Header Text
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 24)
    canvas.drawCentredString(width / 2, height - 55, "Learning Hub")

    canvas.setFont("Helvetica", 12)
    canvas.drawCentredString(width / 2, height - 72, "LEARNING & DEVELOPMENT (L&D) DIVISION")

    # Bottom Seal & Ribbon Graphics
    canvas.setFillColor(colors.HexColor('#D4AF37'))
    canvas.circle(width / 2, 85, 30, fill=1, stroke=0)
    canvas.setFillColor(colors.HexColor('#003366'))
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawCentredString(width / 2, 88, "OFFICIAL")
    canvas.drawCentredString(width / 2, 76, "VERIFIED")

    # Footer Disclaimer
    canvas.setFillColor(colors.HexColor('#555555'))
    canvas.setFont("Helvetica-Oblique", 8)
    canvas.drawCentredString(width / 2, 35, "This certificate is officially generated by Learning Hub L&D Management System.")

    canvas.restoreState()


def generate_certificate_pdf(learner_name, course_name, completion_date_str, certificate_id, output_path):
    """
    Generates a PDF certificate file using ReportLab landscape layout.
    """
    doc = SimpleDocTemplate(
        output_path,
        pagesize=landscape(letter),
        leftMargin=40,
        rightMargin=40,
        topMargin=90,
        bottomMargin=90
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CertTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=28,
        leading=34,
        textColor=colors.HexColor('#003366'),
        alignment=1, # Center
        spaceAfter=15
    )

    subtitle_style = ParagraphStyle(
        'CertSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#555555'),
        alignment=1,
        spaceAfter=15
    )

    name_style = ParagraphStyle(
        'CertName',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=26,
        leading=30,
        textColor=colors.HexColor('#990000'), # Aditya Red Accent
        alignment=1,
        spaceAfter=15
    )

    body_style = ParagraphStyle(
        'CertBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        leading=20,
        textColor=colors.HexColor('#333333'),
        alignment=1,
        spaceAfter=20
    )

    course_style = ParagraphStyle(
        'CertCourse',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#003366'),
        alignment=1,
        spaceAfter=25
    )

    id_style = ParagraphStyle(
        'CertID',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#444444'),
        alignment=0
    )

    date_style = ParagraphStyle(
        'CertDate',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#444444'),
        alignment=2
    )

    elements = []

    elements.append(Paragraph("CERTIFICATE OF COMPLETION", title_style))
    elements.append(Paragraph("PROUDLY PRESENTED TO", subtitle_style))
    elements.append(Paragraph(learner_name.upper(), name_style))
    elements.append(Paragraph("for successfully mastering and completing the professional L&D course", body_style))
    elements.append(Paragraph(f"<b>{course_name}</b>", course_style))

    elements.append(Spacer(1, 20))

    # Meta Table: Certificate ID & Date / Signature placeholders
    meta_data = [
        [
            Paragraph(f"<b>Certificate ID:</b> {certificate_id}", id_style),
            Paragraph(f"<b>Issued On:</b> {completion_date_str}", date_style)
        ],
        [
            Paragraph("_______________________<br/><b>L&D Lead Signature</b>", id_style),
            Paragraph("_______________________<br/><b>Head of Academics</b>", date_style)
        ]
    ]

    table = Table(meta_data, colWidths=[340, 340])
    table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
    ]))

    elements.append(table)

    doc.build(elements, onFirstPage=draw_certificate_background)
    return output_path
